@host = http://localhost:8080
@contentType = application/json

###

GET {{host}}/books

###

POST {{host}}/books
Content-Type: {{contentType}}

{
    "title": "Start with Why",
    "author": "Simon Sinek"
}

###

GET {{host}}/books/1

###

PATCH {{host}}/books/1
Content-Type: {{contentType}}

{
    "title": "The Infinity Game"
}
